### ISSUE TITLE
Exception handling when no input switch option is found

### ISSUE THREAD

**Issue by mgarcia01752** [Comcast/Oscar#29]
>java -jar oscar.jar -x DPoE.bin
/* OSCAR -> OpenSource Cable modem file AssembleR v2.1 */
Exception in thread "main" java.lang.NullPointerException
        at com.comcast.oscar.cli.CommandRun.run(CommandRun.java:246)
        at com.comcast.oscar.cli.Main.main(Main.java:50)

>java -jar oscar.jar -x -i DPoE.bin

**Comment by aflick** [comment]
Fixed
